name = "owari-shop"
workers_dev = true
compatibility_date = "2023-01-15"
main = "build/worker/shim.mjs"
vars = { WORKERS_RS_VERSION = "0.0.12" }
routes = [
    "owari.shop/*",
    "*.owari.shop/*",
]

[build]
command = "cargo install -q worker-build && worker-build --release" # required

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
