name: main CI

concurrency:
  group: main
  cancel-in-progress: false

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup Wrangler
        run: npm i -g wrangler
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: Publish
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler publish
