name: PR CI

concurrency:
  group: pull-request-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup Wrangler
        run: npm i -g wrangler
      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: Publish
        run: wrangler publish --dry-run

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
          components: rustfmt, clippy
      - name: Run check
        run: cargo check --target wasm32-unknown-unknown
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy -- -D warnings
